name: Update from First Repository

on:
  repository_dispatch:
    types: [sync-from-first]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy dist folder from First Repository
        run: |
          git clone https://github.com/KoruJuriSan/network-addr-calculator.git first-repo
          cp -R ./first-repo/dist .

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update dist folder from First Repository"
          git push origin main
