name: Update Second Repository

on:
  push:
    branches:
      - main  # Replace with the appropriate branch name in the second repository

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Second Repository
      uses: actions/checkout@v2

    - name: Add First Repository as Remote
      run: git remote add upstream https://github.com/KoruJuriSan/network-addr-calculator.git

    - name: Fetch Latest Changes from First Repository
      run: git fetch upstream

    - name: Check for Changes in First Repository's dist Folder
      id: check_changes
      run: |
        git diff --quiet HEAD upstream/master -- dist/
        echo "::set-output name=changed::$(if [ $? -eq 1 ]; then echo true; else echo false; fi)"

    - name: Merge Changes from First Repository's dist Folder
      run: |
        if [[ "${{ steps.check_changes.outputs.changed }}" == "true" ]]; then
          git merge upstream/master --no-commit --no-ff --strategy-option=theirs --no-edit
          git rm -r --cached dist/
          git clean -fd dist/
          git commit -m "Update second repository with dist folder from first repository"
        else
          echo "No changes detected in the dist folder. Skipping update."
        fi

    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
